- name: Vercel Deploy Action
  # You may pin to the exact commit or the version.
  # uses: ngduc/vercel-deploy-action@3bb54deb2d890d317a5df89c4d2295a0c32e6dc6
  uses: ngduc/vercel-deploy-action@v19.0.12
  with:
    # Vercel command line. (can be override with "now" CLI)
    vercel-cli: # optional, default is vercel
    # Vercel token
    vercel-token: 
    # 
    vercel-args: # optional, default is 
    # if you want to comment on pr and commit, set true, default: true
    github-comment: # optional, default is true
    # if you want to comment on pr and commit, set token
    github-token: # optional
    # if you want to create github deployment, set true, default: false
    github-deployment: # optional, default is false
    # the working directory
    working-directory: # optional
    # Vercel CLI 17+, ❗️  The `name` property in vercel.json is deprecated (https://zeit.ink/5F)
    vercel-project-id: # optional
    # Vercel CLI 17+, ❗️  The `name` property in vercel.json is deprecated (https://zeit.ink/5F)
    vercel-org-id: # optional
    # If you are work in team scope, you should set this value to your team id.
    scope: # optional
    # zeit.co token
    zeit-token: 
    # 
    now-args: # optional, default is 
    # Vercel CLI 17+, ❗️  The `name` property in vercel.json is deprecated (https://zeit.ink/5F)
    now-project-id: # optional
    # Vercel CLI 17+, ❗️  The `name` property in vercel.json is deprecated (https://zeit.ink/5F)
    now-org-id: # optional
